language: node_js
node_js:
  - "12.13.0"
before_install:
  - npm i -g cross-env
before_script:
  - npm install
script:
  - npm run build
deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  local_dir: "./dist"