language: node_js
node_js:
  - "12.13.0"
before_install:
  - npm i -g cross-env
before_script:
  - npm install
script:
  - npm run build
deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  fqdn: gabormolnar.dev